# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UIs/login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QFile, QTextStream
from GUI.Scripts.sign_window import Ui_signinsignup_window
from GUI.Scripts.login_window import Ui_login_window
from GUI.Scripts.main_window import Ui_main_window
from GUI.Scripts.verify_window import Ui_verify_window
from Scripts.login import Login


class Ui_extension_login_window(object):
    def setupUi(self, ext_login_window):
        ext_login_window.setObjectName("login_window")
        ext_login_window.resize(527, 264)
        ext_login_window.setFixedSize(527, 264)
        self.login_line_2 = QtWidgets.QLineEdit(ext_login_window)
        self.login_line_2.setGeometry(QtCore.QRect(20, 150, 481, 31))
        self.login_line_2.setObjectName("login_line_2")
        self.login_line_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_label_2 = QtWidgets.QLabel(ext_login_window)
        self.login_label_2.setGeometry(QtCore.QRect(20, 120, 81, 19))
        self.login_label_2.setObjectName("login_label_2")
        self.login_line_1 = QtWidgets.QLineEdit(ext_login_window)
        self.login_line_1.setGeometry(QtCore.QRect(20, 50, 481, 31))
        self.login_line_1.setObjectName("login_line_1")
        self.login_label_1 = QtWidgets.QLabel(ext_login_window)
        self.login_label_1.setGeometry(QtCore.QRect(20, 20, 81, 19))
        self.login_label_1.setObjectName("login_label_1")
        self.login_button_1 = QtWidgets.QPushButton(ext_login_window)
        self.login_button_1.setGeometry(QtCore.QRect(110, 220, 100, 31))
        self.login_button_1.setObjectName("login_button_1")
        self.login_button_1.clicked.connect(lambda: self.login(ext_login_window))
        self.login_button_2 = QtWidgets.QPushButton(ext_login_window)
        self.login_button_2.setGeometry(QtCore.QRect(310, 220, 100, 31))
        self.login_button_2.setObjectName("login_button_2")
        self.login_button_2.clicked.connect(lambda: self.cancel(ext_login_window))

        self.retranslateUi(ext_login_window)
        QtCore.QMetaObject.connectSlotsByName(ext_login_window)

    def retranslateUi(self, ext_login_window):
        _translate = QtCore.QCoreApplication.translate
        ext_login_window.setWindowTitle(_translate("login_window", "Login"))
        self.login_label_2.setText(_translate("login_window", "Password"))
        self.login_label_1.setText(_translate("login_window", "Username"))
        self.login_button_1.setText(_translate("login_window", "Login"))
        self.login_button_2.setText(_translate("login_window", "Cancel"))

    def login(self, ext_login_window):
        self.session = Login(self.login_line_1.text(), self.login_line_2.text())
        if self.session.login():
            ext_login_window.close()

            signinsignup_window = QtWidgets.QWidget()
            ui_signinsignup_window = Ui_signinsignup_window()
            ui_signinsignup_window.setupUi(signinsignup_window)

            login_window = QtWidgets.QWidget()
            ui_login_window = Ui_login_window()
            ui_login_window.setupUi(login_window, signinsignup_window)

            main_window = QtWidgets.QMainWindow()
            ui_main_window = Ui_main_window()
            ui_main_window.setupUi(main_window, login_window, self)

            verify_window = QtWidgets.QWidget()
            ui_verify_window = Ui_verify_window()
            ui_verify_window.setupUi(verify_window, main_window, self)
            ui_verify_window.verify_line_1.setText(sys.argv[1])
            verify_window.show()
            ui_verify_window.verify(self)
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error")
            msg.setText("Login Failed!")
            msg.setInformativeText("The username or password is incorrect")
            msg.setIcon(QMessageBox.Critical)
            msg.setStandardButtons(QMessageBox.Ok)
            x = msg.exec_()

    def cancel(self, ext_login_window):
        ext_login_window.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    file = QFile("dark/stylesheet.qss")
    file.open(QFile.ReadOnly | QFile.Text)
    stream = QTextStream(file)
    app.setStyleSheet(stream.readAll())

    ext_login_window = QtWidgets.QWidget()
    ui = Ui_extension_login_window()
    ui.setupUi(ext_login_window)
    ext_login_window.show()
    sys.exit(app.exec_())
