# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UIs/create_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import re
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from Scripts.create_account import CreateAccount


class Ui_create_window(object):
    def setupUi(self, create_window, signinsignup_window):
        create_window.setObjectName("create_window")
        create_window.resize(518, 593)
        create_window.setFixedSize(518, 593)
        self.create_title = QtWidgets.QLabel(create_window)
        self.create_title.setGeometry(QtCore.QRect(90, 10, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.create_title.setFont(font)
        self.create_title.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.create_title.setObjectName("create_title")
        self.create_label_1 = QtWidgets.QLabel(create_window)
        self.create_label_1.setGeometry(QtCore.QRect(10, 100, 161, 19))
        self.create_label_1.setObjectName("create_label_1")
        self.create_line_2 = QtWidgets.QLineEdit(create_window)
        self.create_line_2.setGeometry(QtCore.QRect(10, 230, 501, 31))
        self.create_line_2.setObjectName("create_line_2")
        self.create_label_2 = QtWidgets.QLabel(create_window)
        self.create_label_2.setGeometry(QtCore.QRect(10, 200, 170, 19))
        self.create_label_2.setObjectName("create_label_2")
        self.create_line_1 = QtWidgets.QLineEdit(create_window)
        self.create_line_1.setGeometry(QtCore.QRect(10, 130, 501, 31))
        self.create_line_1.setObjectName("create_line_1")
        self.create_label_3 = QtWidgets.QLabel(create_window)
        self.create_label_3.setGeometry(QtCore.QRect(10, 300, 81, 19))
        self.create_label_3.setObjectName("create_label_3")
        self.create_line_4 = QtWidgets.QLineEdit(create_window)
        self.create_line_4.setGeometry(QtCore.QRect(10, 430, 501, 31))
        self.create_line_4.setObjectName("create_line_4")
        self.create_line_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.create_line_3 = QtWidgets.QLineEdit(create_window)
        self.create_line_3.setGeometry(QtCore.QRect(10, 330, 501, 31))
        self.create_line_3.setObjectName("create_line_3")
        self.create_line_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.create_label_4 = QtWidgets.QLabel(create_window)
        self.create_label_4.setGeometry(QtCore.QRect(10, 400, 131, 19))
        self.create_label_4.setObjectName("create_label_4")
        self.create_button_1 = QtWidgets.QPushButton(create_window)
        self.create_button_1.setGeometry(QtCore.QRect(70, 520, 131, 31))
        self.create_button_1.setObjectName("create_button_1")
        self.create_button_1.clicked.connect(
            lambda: self.createAcc(create_window, signinsignup_window)
        )
        self.create_button_2 = QtWidgets.QPushButton(create_window)
        self.create_button_2.setGeometry(QtCore.QRect(330, 520, 121, 31))
        self.create_button_2.setObjectName("create_button_2")
        self.create_button_2.clicked.connect(
            lambda: self.cancel(create_window, signinsignup_window)
        )

        self.retranslateUi(create_window)
        QtCore.QMetaObject.connectSlotsByName(create_window)

    def retranslateUi(self, create_window):
        _translate = QtCore.QCoreApplication.translate
        create_window.setWindowTitle(_translate("create_window", "Create Account"))
        self.create_title.setText(_translate("create_window", "Create Account"))
        self.create_label_1.setText(_translate("create_window", "Wallet Address"))
        self.create_label_2.setText(
            _translate("create_window", "Infura Görli Endpoint")
        )
        self.create_label_3.setText(_translate("create_window", "Password"))
        self.create_label_4.setText(_translate("create_window", "Confirm Password"))
        self.create_button_1.setText(_translate("create_window", "Create account"))
        self.create_button_2.setText(_translate("create_window", "Cancel"))

    def validateRegex(self, inp, exp):
        regex = re.compile(exp, re.I)
        match = regex.match(str(inp))
        return bool(match)

    def createAcc(self, create_window, signinsignup_window):
        if self.create_line_3.text() == self.create_line_4.text():
            if self.validateRegex(self.create_line_1.text(), "^0x[a-fA-F0-9]{40}$"):
                if self.validateRegex(
                    self.create_line_2.text(),
                    "(^(https?\:\/\/)?((www\.)?goerli\.infura\.io\/v3\/)[\S]{32})",
                ):
                    acc = CreateAccount(
                        self.create_line_1.text(),
                        self.create_line_2.text(),
                        self.create_line_3.text(),
                    )
                    if acc.createAccount():
                        self.showMsgBox(
                            "Success", "User successfuly created!", "", False, False
                        )
                        self.cancel(create_window, signinsignup_window)
                    else:
                        self.showMsgBox(
                            "Error", "Username already exists!", "", True, False
                        )
                else:
                    self.showMsgBox(
                        "Error",
                        "Invalid Rinkeby URL!",
                        "",
                        True,
                        False,
                    )
            else:
                self.showMsgBox(
                    "Error",
                    "Invalid Wallet Address!",
                    "Must be a valid ETH wallet address",
                    True,
                    False,
                )
        else:
            self.showMsgBox("Error", "Passwords do not match!", "", True, False)

    def showMsgBox(self, title, text, inform, err, cancel):
        msg = QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(text)
        msg.setInformativeText(inform)
        if err:
            msg.setIcon(QMessageBox.Critical)
        else:
            msg.setIcon(QMessageBox.Information)
        if cancel:
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        else:
            msg.setStandardButtons(QMessageBox.Ok)
        x = msg.exec_()
        return x

    def cancel(self, create_window, signinsignup_window):
        signinsignup_window.show()
        create_window.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    create_window = QtWidgets.QWidget()
    ui = Ui_create_window()
    ui.setupUi(create_window)
    create_window.show()
    sys.exit(app.exec_())
