# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/UIs/details_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_details_window(object):
    def setupUi(self, details_window, verify_results_window, data):
        details_window.setObjectName("details_window")
        details_window.resize(476, 271)
        details_window.setFixedSize(476, 271)
        self.tableWidget = QtWidgets.QTableWidget(details_window)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 451, 192))
        self.tableWidget.setObjectName("tableWidget")
        attrsLen = len(data[2])
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setHorizontalScrollMode(
            QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel
        )
        self.tableWidget.setVerticalScrollMode(
            QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel
        )
        self.tableWidget.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem())
        self.tableWidget.setRowCount(4 + attrsLen)
        for i in range(4 + attrsLen):
            self.tableWidget.setVerticalHeaderItem(i, QtWidgets.QTableWidgetItem())
        self.details_button_1 = QtWidgets.QPushButton(details_window)
        self.details_button_1.setGeometry(QtCore.QRect(180, 230, 100, 31))
        self.details_button_1.setObjectName("details_button_1")
        self.details_button_1.clicked.connect(
            lambda: self.cancel(details_window, verify_results_window)
        )

        self.retranslateUi(details_window, data)
        QtCore.QMetaObject.connectSlotsByName(details_window)

    def retranslateUi(self, details_window, data):
        _translate = QtCore.QCoreApplication.translate
        details_window.setWindowTitle(_translate("details_window", "Details"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("details_window", "Attribute"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("details_window", "Address"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("details_window", "URL"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("details_window", "Revoked"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("details_window", "Votes"))
        attrsLen = len(data[2])
        for i in range(attrsLen):
            item = self.tableWidget.verticalHeaderItem(i + 4)
            item.setText(_translate("details_window", data[2][i].split(":")[0]))
        self.details_button_1.setText(_translate("details_window", "Close"))
        self.populateTable(data)

    def populateTable(self, data):
        attrsLen = len(data[2])
        columnPosition = 0
        self.tableWidget.setItem(0, columnPosition, QtWidgets.QTableWidgetItem(data[0]))
        self.tableWidget.setItem(1, columnPosition, QtWidgets.QTableWidgetItem(data[1]))
        self.tableWidget.setItem(
            2, columnPosition, QtWidgets.QTableWidgetItem(str(data[4]))
        )
        self.tableWidget.setItem(
            3, columnPosition, QtWidgets.QTableWidgetItem(str(data[5]))
        )
        self.tableWidget.resizeColumnToContents(0)
        self.tableWidget.resizeColumnToContents(1)
        self.tableWidget.resizeColumnToContents(2)
        self.tableWidget.resizeColumnToContents(3)
        for i in range(attrsLen):
            self.tableWidget.setItem(
                i + 4,
                columnPosition,
                QtWidgets.QTableWidgetItem(data[2][i].split(": ")[1]),
            )
            self.tableWidget.resizeColumnToContents(i + 4)

    def cancel(self, details_window, verify_results_window):
        verify_results_window.show()
        details_window.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    details_window = QtWidgets.QWidget()
    ui = Ui_details_window()
    ui.setupUi(details_window)
    details_window.show()
    sys.exit(app.exec_())
