# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/UIs/create_certificate_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog, window_title, window_text):
        dialog.setObjectName("dialog")
        dialog.resize(362, 145)
        dialog.setFixedSize(362, 145)
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(90, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(dialog, window_title, window_text)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog, window_title, window_text):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", window_title))
        self.label.setText(_translate("dialog", window_text))
        self.label.adjustSize()
        self.label.setAlignment(QtCore.Qt.AlignCenter)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
